language: php

php: [5.3, 5.4, 5.5, hhvm]

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  exclude:
    - php: hhvm
      env: SYMFONY_VERSION='2.3.*'
    - php: hhvm
      env: SYMFONY_VERSION='2.5.*@dev'

env:
  - SYMFONY_VERSION='2.3.*'
  - SYMFONY_VERSION='2.4.*'
  - SYMFONY_VERSION='2.5.*@dev'

before_script:
  - export WEB_FIXTURES_HOST=http://localhost
  - export WEB_FIXTURES_BROWSER=firefox

  - composer require --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install --dev --prefer-source

  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
  - sudo sed -i -e "s,/var/www,$(pwd)/vendor/behat/mink/tests/Behat/Mink/Driver/web-fixtures,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
